name: pokemon-front-test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Conteneurisation
        run: docker compose up -d

      - name: Test
        run: npm test
