name: pokemon-front-test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configuration Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation des dépendances
        run: npm ci

      - name: Lancement des tests
        run: npm test
