name: pokemon-front

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configuration Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation des dépendances
        run: npm ci

      - name: Lancement des tests
        run: npm test

      - name: Connexion à docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Création de l'image Docker et envoie sur le registry
        run: |
          docker build . -t ghcr.io/davalenzo/pokemon-front-test:${{ matrix.node-version }}
          docker run ghcr.io/davalenzo/pokemon-front-test:${{ matrix.node-version }}
          docker push ghcr.io/davalenzo/pokemon-front-test:${{ matrix.node-version }}
